<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar Ruangan</name>
   <tag></tag>
   <elementGuidId>4c0f9e86-70cc-4483-b5d5-45bf59ed8611</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navMenu-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navMenu-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>969e721e-c40a-4b44-bfe0-14ef80130b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>daftarRuangan.html</value>
      <webElementGuid>510b28f9-8aff-4b8d-bb87-e59726fae5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navMenu-3</value>
      <webElementGuid>753e3cbd-3a02-4215-91e4-4d9fbdc3500b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Ruangan</value>
      <webElementGuid>ea23b317-ddba-4f8e-b852-d35a08ce2d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navMenu-3&quot;)</value>
      <webElementGuid>5e8d77bd-d168-472a-8368-ec872e9dde1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='navMenu-3']</value>
      <webElementGuid>5792e396-5d65-484a-aa56-a100efc9a1e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbar']/ul/li[2]/a</value>
      <webElementGuid>d4d3b054-d1f2-4f47-99ea-fbc574293fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Daftar Ruangan')]</value>
      <webElementGuid>8abd3d22-d8fa-4d00-9aaf-dc983c086677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>3ed38b37-cc68-4ee6-ad52-095cd115b5a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[1]/following::a[2]</value>
      <webElementGuid>ee66ed7f-f5b6-4f48-93ea-3fe61a4eb4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifikasi'])[1]/preceding::a[1]</value>
      <webElementGuid>d630e830-d1e0-45d0-919e-feda110b171c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='profile'])[1]/preceding::a[2]</value>
      <webElementGuid>531836ad-b103-43e9-a8ca-e3b562db33e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar Ruangan']/parent::*</value>
      <webElementGuid>eeb29792-da0d-4aa5-94f9-5a63a4479bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'daftarRuangan.html')]</value>
      <webElementGuid>ee7c85cb-dcd4-41ae-ac6c-00619fd34c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>b242b66d-ae91-4712-bc8c-bf73a55715b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'daftarRuangan.html' and @id = 'navMenu-3' and (text() = 'Daftar Ruangan' or . = 'Daftar Ruangan')]</value>
      <webElementGuid>50c126f2-6b53-44f0-9f1a-a423b2b8f9d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
