<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log-In</name>
   <tag></tag>
   <elementGuidId>72ae31c7-bbab-45bd-910e-53b9a64fa505</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Log-In')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>203fedaf-0e08-45a0-b337-8f76b1072869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>pages/dashboard.html</value>
      <webElementGuid>37c72e1c-fe27-41de-821a-d888287b6244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-block mb-4 btn-login-register</value>
      <webElementGuid>7e96d712-25c6-4e20-ab02-cf4699b4fb51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Log-In
                </value>
      <webElementGuid>d494dff4-2591-4a0d-8cf0-51ddc14e66c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container py-4 d-flex justify-content-center align-items-center vh-100&quot;]/div[@class=&quot;row g-0 col-lg-12 align-items-center&quot;]/div[@class=&quot;col-lg-8 mb-5 mb-lg-0 mx-auto position-relative&quot;]/div[@class=&quot;card cascading-right container-login&quot;]/div[@class=&quot;card-body p-5 shadow-5 text-center&quot;]/form[1]/a[@class=&quot;btn btn-primary btn-block mb-4 btn-login-register&quot;]</value>
      <webElementGuid>cb89262e-a785-434f-b975-2b451a0d6275</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Log-In')]</value>
      <webElementGuid>beaaf195-2323-42c5-80e1-f9f6ec0a2a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign-up'])[1]/following::a[1]</value>
      <webElementGuid>298a2e18-5ca3-463b-ac6d-89a0c547fe8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::a[2]</value>
      <webElementGuid>10b78975-dc66-4a49-9003-93bd9e8801ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log-In']/parent::*</value>
      <webElementGuid>cad577ef-6554-41e1-81ab-a4b213863393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'pages/dashboard.html')]</value>
      <webElementGuid>135e5761-f9c5-4bef-9be0-1e9734290601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>e787b623-d9fd-49c1-9629-628edd7b41ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'pages/dashboard.html' and (text() = '
                  Log-In
                ' or . = '
                  Log-In
                ')]</value>
      <webElementGuid>e820ac7b-5087-4bcc-8a72-f832164fd4fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
