<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Notifikasi</name>
   <tag></tag>
   <elementGuidId>34450d30-88bf-43ea-8e6d-51ca6fec72f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navMenu-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navMenu-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e1233e13-d370-43dd-862d-7d8651c0436e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>notifikasi.html</value>
      <webElementGuid>ada45a3c-9445-4010-8979-ad4f529ee6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navMenu-4</value>
      <webElementGuid>d912c0b9-5ae4-433e-954d-146f5554f0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notifikasi</value>
      <webElementGuid>2e413b20-47f6-4c7f-804d-72ee4aefb854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navMenu-4&quot;)</value>
      <webElementGuid>0969197b-d0da-405e-b854-c2d65dcc25dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='navMenu-4']</value>
      <webElementGuid>79e7b1d9-1943-4755-98a6-671f07900fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbar']/ul/li[3]/a</value>
      <webElementGuid>96187ada-3708-43d8-ad65-637bb98e2a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Notifikasi')]</value>
      <webElementGuid>d6f58320-e32e-4962-82eb-d2e840fec93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Ruangan'])[1]/following::a[1]</value>
      <webElementGuid>5ae0e372-2c86-4a9c-9cac-9f40285c203f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[2]</value>
      <webElementGuid>dea04cda-aeda-41d9-a9b4-0744bbaa4675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='profile'])[1]/preceding::a[1]</value>
      <webElementGuid>c4b8f168-4d93-440b-9774-9aba2703ccdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::a[2]</value>
      <webElementGuid>ef514c36-75f0-45f1-9e6c-c6d9bf3debbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Notifikasi']/parent::*</value>
      <webElementGuid>db21e5d0-1148-4c4e-8155-14369f02f1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'notifikasi.html')]</value>
      <webElementGuid>f6de383d-ab19-44d4-b114-ba6a75a9c963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>46b57b4e-e4dc-4e2e-96f3-8da7f23c7519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'notifikasi.html' and @id = 'navMenu-4' and (text() = 'Notifikasi' or . = 'Notifikasi')]</value>
      <webElementGuid>a2f29135-d7d2-4adb-8f37-0c153b8cbd21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
