<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_profile</name>
   <tag></tag>
   <elementGuidId>14a7d27b-5fb9-4760-91c2-9898e8b239b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navMenu-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navMenu-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>77a2de7a-54e9-4f87-97d8-3ef4cf4a900a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>profile.html</value>
      <webElementGuid>e82f0986-372d-4e8a-a2c4-696096e16c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navMenu-5</value>
      <webElementGuid>52c2d55e-e18e-4be1-a29b-33ac9d3206fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>profile</value>
      <webElementGuid>c5cf47d9-feba-42dd-8e22-86a8d4653efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navMenu-5&quot;)</value>
      <webElementGuid>612b8968-4951-44e0-b6eb-64934fe9116e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='navMenu-5']</value>
      <webElementGuid>3d822621-8ee7-4b01-bed9-d17a34977ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbar']/ul/li[4]/a</value>
      <webElementGuid>52c51f29-7130-4ecf-9048-80bf45393970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'profile')]</value>
      <webElementGuid>917bd1c8-c4d8-4dee-a197-f975cb199361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifikasi'])[1]/following::a[1]</value>
      <webElementGuid>b7393066-48bd-419c-9ad9-70afafd7ab07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Ruangan'])[1]/following::a[2]</value>
      <webElementGuid>e2a2bc41-f626-441a-87d6-daab1daa7d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::a[1]</value>
      <webElementGuid>c64d47ee-bd07-4433-b6b3-a8a74bbecd0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='profile']/parent::*</value>
      <webElementGuid>4ea80c8d-9500-47b5-9133-bf61f77f542f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'profile.html')]</value>
      <webElementGuid>3b9e934a-2e2a-4685-a565-0d394b22e989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>eab07cf4-b8b5-4049-b267-ae8d09d74828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'profile.html' and @id = 'navMenu-5' and (text() = 'profile' or . = 'profile')]</value>
      <webElementGuid>a710b3ff-0737-4b50-9651-cec5f2c3c88d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
