<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign-up</name>
   <tag></tag>
   <elementGuidId>1c4060c6-bdce-43fd-aa5c-76fb11af12b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.btn-block.mb-4.btn-login-register</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Sign-up')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fdbe6357-665e-456f-8fe3-66798df6c80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>register.html</value>
      <webElementGuid>f4dd2bc1-0858-4891-b278-91cbb62c3cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-block mb-4 btn-login-register</value>
      <webElementGuid>9609de49-10a5-46d7-be73-65bd7c411cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Sign-up
                </value>
      <webElementGuid>1ab94d75-83c1-4e8c-8fd0-2db111dd3a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container py-4 d-flex justify-content-center align-items-center vh-100&quot;]/div[@class=&quot;row g-0 col-lg-12 align-items-center&quot;]/div[@class=&quot;col-lg-8 mb-5 mb-lg-0 mx-auto position-relative&quot;]/div[@class=&quot;card cascading-right container-login&quot;]/div[@class=&quot;card-body p-5 shadow-5 text-center&quot;]/form[1]/a[@class=&quot;btn btn-primary btn-block mb-4 btn-login-register&quot;]</value>
      <webElementGuid>d1f08bdf-e31b-43ec-920d-52fd0eda6646</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign-up')]</value>
      <webElementGuid>e8c266fa-a79a-4739-a737-8c1f1af995f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::a[1]</value>
      <webElementGuid>746620d6-313d-4fc3-836e-93030a1b431f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email address'])[1]/following::a[1]</value>
      <webElementGuid>5f475b4a-aa2f-4bcd-9544-d176d6c6873e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log-In'])[1]/preceding::a[1]</value>
      <webElementGuid>f21e57e5-0a97-48bb-9951-f978f84a032d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign-up']/parent::*</value>
      <webElementGuid>2acfb402-bda6-4d86-9874-303bd8387b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'register.html')]</value>
      <webElementGuid>ae3e38f9-a7a2-456b-b9df-b34d493ef78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/a</value>
      <webElementGuid>464677e8-dff2-448c-8be9-d05ea15d383a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'register.html' and (text() = '
                    Sign-up
                ' or . = '
                    Sign-up
                ')]</value>
      <webElementGuid>cf5d0150-4d20-484e-a3a7-61c6109813fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
