<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign-up</name>
   <tag></tag>
   <elementGuidId>8703828f-5ac3-46d0-9f16-f5f246a26274</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.btn-block.mb-4.btn-login-register</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7bb6c633-8c87-466d-862c-1abad65171de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>12a4048e-c0a5-44f8-994d-0b9875b2f3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-block mb-4 btn-login-register</value>
      <webElementGuid>295e924a-5045-432d-a78c-109354731f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Sign-up
                </value>
      <webElementGuid>12f12eb7-ee80-41ee-8610-534f42eb6078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container py-4&quot;]/div[@class=&quot;row g-0 align-items-center&quot;]/div[@class=&quot;col-lg-8 mb-5 mb-lg-0 mx-auto position-relative&quot;]/div[@class=&quot;card cascading-right container-login&quot;]/div[@class=&quot;card-body p-5 shadow-5 text-center&quot;]/form[1]/button[@class=&quot;btn btn-primary btn-block mb-4 btn-login-register&quot;]</value>
      <webElementGuid>00675c3d-57a8-45d6-808f-d46dac948e0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>fb7ec165-bcca-454d-88e4-f0a1691345c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log-In'])[1]/following::button[1]</value>
      <webElementGuid>6aaa8c39-1e46-495b-9af3-074a45224e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verify Password'])[1]/following::button[1]</value>
      <webElementGuid>1c4d73e3-e5e2-401d-b180-c07e19a67deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign-up']/parent::*</value>
      <webElementGuid>663470f9-31c1-47cd-ad02-5cb199300d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>0c137256-ee99-40b8-be2f-7ccb5e9051e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                    Sign-up
                ' or . = '
                    Sign-up
                ')]</value>
      <webElementGuid>f5ace602-4d27-4f15-9146-d24aaff83bee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
