<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h6_Urang</name>
   <tag></tag>
   <elementGuidId>8dcdcf14-9ef7-4272-88d1-324ea3c9d7fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='view-detail']/div/div[2]/div[2]/div/h6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>bf224d7c-3cb0-4891-9ef1-850b13fbfd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Urang</value>
      <webElementGuid>90c45a57-1b07-48dd-a4cd-c941019c181a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view-detail&quot;)/div[@class=&quot;container aos-init aos-animate&quot;]/div[@class=&quot;row justify-content-around gy-4&quot;]/div[@class=&quot;col-lg-5 d-flex flex-column&quot;]/div[@class=&quot;data-field-profile&quot;]/h6[1]</value>
      <webElementGuid>783f2238-8d3c-4d40-8937-38a6933bb07d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='view-detail']/div/div[2]/div[2]/div/h6</value>
      <webElementGuid>013f78ce-7c35-40f7-a572-6198d4695573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[1]/following::h6[1]</value>
      <webElementGuid>a0d2ddc7-ae49-4eea-a009-18b51acfc51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/following::h6[1]</value>
      <webElementGuid>c8ed9be4-6534-47e7-a25c-19d6db9f602e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nim'])[1]/preceding::h6[1]</value>
      <webElementGuid>ce5c767e-07d1-421b-9b48-815d3ffbdb1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/preceding::h6[2]</value>
      <webElementGuid>00235f47-4b47-452c-9faa-c311d13ebd42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Urang']/parent::*</value>
      <webElementGuid>5d03550f-3457-4c3d-992d-fd786e2276a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h6</value>
      <webElementGuid>f38057a6-e027-489e-9d7b-0cbaf1953efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Urang' or . = 'Urang')]</value>
      <webElementGuid>7e7e5718-7533-4c48-a8e5-db8fc5a206a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
