<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__hamburger-toggle</name>
   <tag></tag>
   <elementGuidId>c907ecc0-c750-445d-80ca-c775c685811e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hamburger-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='hamburger-toggle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>fdb571db-e61a-488e-a6d4-99187f1818e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hamburger-toggle</value>
      <webElementGuid>2469f100-45e8-406e-95c5-721f46c4e5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile-nav-toggle mobile-nav-show bi bi-list</value>
      <webElementGuid>95c420d3-a84c-4e8c-a712-526c6216eff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hamburger-toggle&quot;)</value>
      <webElementGuid>23ad89c9-f569-4baf-8b6b-430b5fa5c440</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='hamburger-toggle']</value>
      <webElementGuid>a366a007-8c3c-4e1a-94a5-a62cd3b8f4ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navapp']/div/i</value>
      <webElementGuid>8cf53f2d-e647-4225-b490-bb8675c6e117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>649ab886-cf12-4aa5-b872-fdfb1a31b748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'hamburger-toggle']</value>
      <webElementGuid>28bcbbfd-8259-4493-b4d7-0250a6679693</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
