<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_form-control</name>
   <tag></tag>
   <elementGuidId>d7a58dc4-17a1-4e8a-ab42-39543925260d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.form-outline.mb-4 > input.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68647043-6055-4500-8ec8-72f77ebe4b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>073d92eb-1c2a-466a-a043-920f9e6c295c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c239e37b-aa6b-44c4-bcf6-21b13e0243b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container py-4&quot;]/div[@class=&quot;row g-0 align-items-center&quot;]/div[@class=&quot;col-lg-8 mb-5 mb-lg-0 mx-auto position-relative&quot;]/div[@class=&quot;card cascading-right container-login&quot;]/div[@class=&quot;card-body p-5 shadow-5 text-center&quot;]/form[1]/div[@class=&quot;form-outline mb-4&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>259a2fb7-eb41-4279-9615-0efafe51ff35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='email']</value>
      <webElementGuid>0d91d17f-0b95-4733-b4e6-cb2b244a8e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a855ab57-d828-44ae-a064-1cb9367b41a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email']</value>
      <webElementGuid>42af6aa8-638e-419b-804e-0ab0c8d79e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>de1fcc6d-3912-46f1-a12a-af5b7a1e44d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-prfile-modal']/div/div/div[2]/div/div/input</value>
      <webElementGuid>80106d7c-ca96-4b31-973a-a5545a87b35f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>453926dc-0b24-4bcd-a86e-065bd78d2dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>40c4d071-c835-4afe-8dfb-c06b402ced57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
