<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_form-control</name>
   <tag></tag>
   <elementGuidId>9ce8245f-78b9-4c17-99dc-cdd6d0df8185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27be1571-9ede-4241-88f5-a630a2e74637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f366dcd8-78ef-4e2c-9d89-c35a162de929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a091e2b6-e96a-4559-a494-b4b15bdfd14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container py-4&quot;]/div[@class=&quot;row g-0 align-items-center&quot;]/div[@class=&quot;col-lg-8 mb-5 mb-lg-0 mx-auto position-relative&quot;]/div[@class=&quot;card cascading-right container-login&quot;]/div[@class=&quot;card-body p-5 shadow-5 text-center&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 mb-4&quot;]/div[@class=&quot;form-outline&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>56c141b6-2b29-4286-9708-b0338b5a27e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>2f8c1755-affb-468a-b15d-232a4879a31a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>bb701286-9176-4dc7-b5e6-4a0209cec900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password']</value>
      <webElementGuid>76d2c4a3-4289-4c09-8456-74f5cf88cbf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
