<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Home            Daftar Ruangan          _2c075b</name>
   <tag></tag>
   <elementGuidId>e88b8f21-e308-42c0-890e-177280c8a172</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='navbar']/ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>4ea79ba5-a513-400b-8715-49127746ad12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Home
            Daftar Ruangan
            Notifikasi
            profile
            Login
          </value>
      <webElementGuid>8e58195d-4fb5-4241-a48d-97adeca47d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/ul[1]</value>
      <webElementGuid>df2ff263-10ce-4491-8cad-ad43ef39b745</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbar']/ul</value>
      <webElementGuid>0122eacf-dec3-4aa0-a203-ab514126f8ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[1]/following::ul[1]</value>
      <webElementGuid>50041835-0248-474d-8575-3466140b8ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul</value>
      <webElementGuid>fe82111c-07fe-4aa9-8c2e-df4c5465e464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = '
            Home
            Daftar Ruangan
            Notifikasi
            profile
            Login
          ' or . = '
            Home
            Daftar Ruangan
            Notifikasi
            profile
            Login
          ')]</value>
      <webElementGuid>12201105-35e5-4223-b8c3-2476a57ff8bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
